name: dynamic_color_ffi
description: A new Flutter FFI plugin project.
version: 0.0.1
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.1
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.15.2
  meta: ^1.17.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  materium_lints:
    path: ../materium_lints
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: DynamicColorAndroid
        ffiPlugin: true
