name: material
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  layout:
    path: ../layout
  androidx_graphics_shapes: ^1.0.0
  meta: ^1.17.0
  material_symbols_icons: ^4.2892.0
  collection: ^1.19.1
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.1
