name: materium
description: Get Android app updates straight from the source.
version: 1.2.9+2325
repository: https://github.com/deminearchiver/materium
publish_to: none

workspace:
  - dynamic_color
  - dynamic_color/example
  - materium_tools

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  # SDK dependencies
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Git dependencies
  layout:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      path: packages/layout
  material:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      path: packages/material
  android_package_installer: # TODO: See if PR will be accepted (dev may not be active), else remove this comment
    git:
      url: https://github.com/ImranR98/android_package_installer
      ref: main
  android_package_manager: # TODO: Make PR and switch to upstream
    git:
      url: https://github.com/ImranR98/android_package_manager
      ref: master
  shared_storage: # TODO: Is this maintained?
    git:
      url: https://github.com/AlexBacich/shared-storage
      ref: master
  shizuku_apk_installer:
    git:
      url: https://github.com/wilver06w/shizuku_apk_installer
      ref: master

  # Hosted dependencies
  meta: ^1.17.0
  path_provider: ^2.1.5
  flutter_fgbg: ^0.7.1
  flutter_local_notifications: ^19.5.0
  provider: ^6.1.5+1
  http: ^1.6.0
  webview_flutter: ^4.13.0
  html: ^0.15.6
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  fluttertoast: ^9.0.0
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  sqflite: ^2.4.2
  easy_localization: ^3.0.8
  android_intent_plus: ^6.0.0
  flutter_archive: ^6.0.4
  hsluv: ^1.1.3
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  bcrypt: ^1.2.0
  app_links: ^7.0.0
  background_fetch: ^1.5.0
  flex_color_picker: ^3.8.0
  markdown: ^7.3.0
  flutter_typeahead: ^5.2.0
  battery_plus: ^7.0.0
  flutter_charset_detector: ^5.0.0
  flutter_foreground_task: ^9.2.0
  material_symbols_icons: ^4.2892.0
  flutter_markdown_plus: ^1.0.7
  skeletonizer: ^2.1.2
  super_keyboard: ^0.3.1
  super_editor: ^0.3.0-dev.47
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.2.3
  vector_graphics: ^1.1.19
  collection: ^1.19.1
  syntax_highlight: ^0.5.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  drift_sqflite: ^2.0.1
  talker_flutter: ^5.1.9
  talker_dio_logger: ^5.1.9
  dio: ^5.9.0
  retrofit: ^4.9.2
  cronet_http: ^1.7.0
  device_info_ffi: ^1.0.3
  dynamic_color_ffi: ^1.0.2
  screen_corners_ffi: ^1.0.2
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  rhttp: ^0.15.0
  pub_semver: ^2.2.0

dev_dependencies:
  # Hosted dependencies
  deminearchiver_lints: ^1.1.1
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  flutter_gen_runner: ^5.12.0
  drift_dev: ^2.30.0
  retrofit_generator: ^10.2.1
  slang_build_runner: ^4.11.0
  slang_gpt: ^0.11.1
  fastforge: ^0.6.6
  pubspec_generator: ^5.0.0

dependency_overrides:
  # Git dependencies
  layout:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      ref: a33af4020e9c05dc0883eaa39ee7f15c1d6da663
      path: packages/layout
  material:
    git:
      url: https://github.com/deminearchiver/dart-flutter-packages.git
      ref: a33af4020e9c05dc0883eaa39ee7f15c1d6da663
      path: packages/material

  # Hosted dependencies
  archive: ^4.0.7 # fastforge uses outdated version
  device_info_plus: ^12.3.0 # Needed for unknown reasons
  material_color_utilities: ^0.13.0 # Flutter pinned dependency
  meta: ^1.17.0 # Always use latest version
  uuid: ^4.5.2 # fastforge uses outdated version

flutter:
  uses-material-design: true
  generate: false
  assets:
    # Certificates
    - assets/ca/

    # Graphics
    - assets/graphics/

    # App icons
    - assets/ic_launcher/

    # Translation files for easy_localization
    - assets/translations/

    # Open Font Licenses
    - assets/fonts/firacode/OFL.txt
    - assets/fonts/googlesans/OFL.txt
    - assets/fonts/googlesanscode/OFL.txt
    - assets/fonts/googlesansflex/OFL.txt
    - assets/fonts/robotoflex/OFL.txt
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/firacode/FiraCode-VariableFont_wght.ttf
          style: normal
    - family: Google Sans
      fonts:
        - asset: assets/fonts/googlesans/GoogleSans-VariableFont_GRAD,opsz,wght.ttf
          style: normal
        - asset: assets/fonts/googlesans/GoogleSans-Italic-VariableFont_GRAD,opsz,wght.ttf
          style: italic
    - family: Google Sans Code
      fonts:
        - asset: assets/fonts/googlesanscode/GoogleSansCode-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/googlesanscode/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/googlesansflex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/robotoflex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
