name: materium_fonts
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  materium_lints:
    path: ../materium_lints
  flutter_gen_runner: ^5.12.0
  build_runner: ^2.10.4

flutter:
  assets:
    - assets/fonts/firacode/OFL.txt
    - assets/fonts/googlesanscode/OFL.txt
    - assets/fonts/googlesansflex/OFL.txt
    - assets/fonts/robotoflex/OFL.txt
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/firacode/FiraCode-VariableFont_wght.ttf
          style: normal
    - family: Google Sans Code
      fonts:
        - asset: assets/fonts/googlesanscode/GoogleSansCode-VariableFont_wght.ttf
          style: normal
        - asset: assets/fonts/googlesanscode/GoogleSansCode-Italic-VariableFont_wght.ttf
          style: italic
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/googlesansflex/GoogleSansFlex-VariableFont_GRAD,ROND,opsz,slnt,wdth,wght.ttf
    - family: Roboto Flex
      fonts:
        - asset: assets/fonts/robotoflex/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf
