name: dynamic_color
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  async: ^2.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  deminearchiver_lints: ^1.1.1
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
  freezed: ^3.2.3

flutter:
  plugin:
    platforms:
      android:
        package: dev.deminearchiver.dynamic_color
        pluginClass: DynamicColorPlugin
      ios:
        pluginClass: DynamicColorPlugin
      linux:
        pluginClass: DynamicColorPlugin
      macos:
        pluginClass: DynamicColorPlugin
      windows:
        pluginClass: DynamicColorPluginCApi
      web:
        pluginClass: DynamicColorWeb
        fileName: dynamic_color_web.dart
