name: materium_tools
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  meta: ^1.17.0
  http: ^1.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  async: ^2.13.0
  dio: ^5.9.0

dev_dependencies:
  deminearchiver_lints: ^1.1.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2
  test: ^1.26.3
