name: materium_tools
description: A sample command-line application.
version: 1.0.0
homepage: https://github.com/deminearchiver/materium
repository: https://github.com/deminearchiver/materium/tree/main/materium_tools
issue_tracker: https://github.com/deminearchiver/materium/issues
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.1
  meta: ^1.18.0
  http: ^1.6.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  async: ^2.13.0
  dio: ^5.9.0

dev_dependencies:
  build_runner: ^2.10.5
  deminearchiver_lints: ^1.1.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2
